### PR TITLE
Added way to download MODSCAG to HMA extent

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR adds a script `modscag_download.py` that provides a way to download MODSCAG dataset. It has been subsetted to only HMA region. This is basically a wrapper to `snow_download_by_tile.py`. Also, once download is completed it merges the tiles to single GeoTiff file.

### CODE REVIEW

**Comment by lsetiawan** [comment]
Also another comment for this script. Must be run with Python 2.7!

**Comment by aaarendt** [comment]
@lsetiawan the .yml file installs Python 3.6...is this a mistake w.r.t. your last comment?

**Comment by lsetiawan** [comment]
@aaarendt This is not a mistake, for most of himat work, it will be in Python 3.6. For this MODSCAG, Python 2.7 should be used, since the code from NASA is in 2.7. I haven't worked on editing/testing on Python 3.6.

**Comment by lsetiawan** [comment]
Additionally, `progressbar2` should be installed. `conda install -c conda-forge progressbar2`

**Comment by lsetiawan** [comment]
@aaarendt It is easy to clone the himat environment you have now and then do `conda install -c conda-forge python=2.7`, this will make all your packages to Python 2.7.

**Comment by aaarendt** [comment]
got it - I thought you made that yml specifically for this modscag stuff. Will give this a try now

**Comment by lsetiawan** [comment]
> got it - I thought you made that yml specifically for this modscag stuff. Will give this a try now

No, It is meant to be a general yml for HiMAT work.

**Comment by aaarendt** [comment]
testing on about 15 files. Works fine until it tries to merge:
image

**Comment by lsetiawan** [comment]
How did you run it? Try specifying `--outpath`

**Comment by aaarendt** [comment]
image

This is the command I issued. I did specify outpath and it copied the requested .tif files to that directory.

**Pull request merged**
